---
# Set etcd backup directory
- set_fact:
    backup_dir_name: "{{ etcd_backup_prefix }}{{ etcd_backup_tag }}{{ etcd_backup_suffix }}"

- set_fact:
    etcd_backup_dir: "{{ etcd_data_dir }}/{{ backup_dir_name }}"

- name: Get rkt pod list
  command: rkt list --format=json
  register: rktlist

- name: Get etcd pod(s)
  set_fact: etcd_pods="{{ rktlist.stdout | from_json | json_query(etcd_pods_query) }}"
  vars:
    etcd_pods_query: "[?state=='running' && contains(app_names, 'etcd')].name"

- fail:
    msg: "Failed finding a single running etcd pod"
  when:
    - etcd_pods|length != 1

- set_fact:
    etcd_pod_id: "{{ etcd_pods[0] }}"

- set_fact:
    etcdctl_cmd_v2: "{{ 'rkt enter ' + etcd_pod_id + ' /usr/local/bin/etcdctl' }}"
    etcdctl_cmd_v3: "{{ 'rkt enter ' + etcd_pod_id + ' /usr/bin/env ETCDCTL_API=3 /usr/local/bin/etcdctl' }}"
